###
### -----------------------
### Patient Assist.........
### Systemudvikling........
### Cph. Business School...
### -----------------------
###

@url=http://localhost:9999/api

###
# @name REGISTER

POST {{url}}/auth/register
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin",
    "first_name": "John",
    "middle_name": "Doe",
    "last_name": "Smith",
    "roles": ["admin"],
    "sections": [1, 2, 5]
}

###
# @name LOGIN

POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin"
}

###
# @name LOGIN FAIL PASSWORD

POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "fail"
}

###
# @name LOGIN FAIL EMAIL

POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "fail@example.com",
    "password": "admin"
}
