###
### -----------------------
### Patient Assist.........
### Systemudvikling........
### Cph. Business School...
### -----------------------
###

@url=http://localhost:9999/api

###
# @name REGISTER

POST {{url}}/auth/register
Content-Type: application/json

{
  "email": "admin5@test.dk",
  "password": "admin5",
  "firstName": "John",
  "middleName": "Doe",
  "lastName": "Smith",
  "roles": [
    "admin", "doctor", "guest"
  ],
  "sections": [
    1,
    2,
    5
  ]
}

###
# @name LOGIN DEFAULT ADMIN

POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "admin@test.dk",
  "password": "admin"
}

###
# @name LOGIN

POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "admin5@test.dk",
  "password": "admin5"
}
