# Get all dishes
GET {{url}}api/dishes/all
Accept: application/json

###

# Get dish by ID
GET {{url}}api/dishes/1
Accept: application/json

###

# Filtered (by status & allergen)
GET {{url}}api/dishes/filter?status=TILGÆNGELIG&allergen=GLUTEN
Accept: application/json

###

# Currently available
GET {{url}}api/dishes/available
Accept: application/json

###

#Most ordered (top 5)
GET {{url}}api/dishes/most-ordered
Accept: application/json
###


# Create a new dish
POST {{url}}api/dishes/new
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Stegt flæsk",
  "description": "Klassisk dansk ret med persillesovs",
  "kcal": 500,
  "protein": 25,
  "carbohydrates": 20,
  "fat": 30,
  "allergens": ["LAKTOSE"],
  "availableFrom": "2025-05-11",
  "availableUntil": "2025-05-20",
  "recipe": {
    "title": "Stegt flæsk med persillesovs",
    "instructions": "Steg flæsk, kog kartofler, lav sovs",
    "ingredients": [
      { "name": "Flæsk" },
      { "name": "Kartofler" },
      { "name": "Mælk" },
      { "name": "Persille" }
    ]
  }
}

###

# Delete a dish
DELETE {{url}}api/dishes/1
Authorization: Bearer {{jwt_token}}


###

# Patch a single field (e.g. name)
PATCH {{url}}api/dishes/1/name
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

Flæskesteg med sovs

###

# Patch recipe and allergens
PATCH {{url}}api/dishes/1/recipe-and-allergens
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "recipe": {
    "title": "Rugbrød med rejer",
    "instructions": "Læg rejer på rugbrød, pres citron over",
    "ingredients": [
      { "name": "Rugbrød" },
      { "name": "Rejer" },
      { "name": "Citron" }
    ]
  },
  "allergens": ["SKALDYR", "CITRON"]
}
