### Get all dishes
GET {{url}}/api/dishes
Accept: application/json

### Get dish by ID
GET {{url}}/api/dishes/1
Accept: application/json

### Filtered dishes
GET {{url}}/api/dishes/filter?keyword=flæsk
Accept: application/json

### Get available dishes
GET {{url}}/api/dishes/available
Accept: application/json

### Get most ordered dishes
GET {{url}}/api/dishes/most-ordered
Accept: application/json

### Create new dish
POST {{url}}/api/dishes/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Stegt flæsk",
  "description": "Klassisk dansk ret med persillesovs",
  "kcal": 500,
  "protein": 25,
  "carbohydrates": 20,
  "fat": 30,
  "allergens": ["mælk"],
  "availableFrom": "2025-05-11",
  "availableUntil": "2025-05-20",
  "recipe": "Stegt flæsk, kartofler, persillesovs"
}

### Delete dish
DELETE {{url}}/api/dishes/1
Authorization: Bearer {{token}}

### Update dish name
PATCH {{url}}/api/dishes/1/name
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Flæskesteg med sovs"
}

### Update kcal
PATCH {{url}}/api/dishes/1/kcal
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "kcal": 600
}

### Update recipe and allergens
PATCH {{url}}/api/dishes/1/recipe-and-allergens
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "recipe": "Rugbrød, rejer, citron",
  "allergens": ["skaldyr"]
}
