package dk.patientassist.persistence.ent;

import dk.patientassist.persistence.enums.Role;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a user in the system.
 * Each user has credentials and an associated role for authorization.
 *
 * Mapped to the database table named "_user".
 * Uses Lombok to generate standard getters and setters.
 */
@NoArgsConstructor
@Getter
@Setter
@Entity
@Table(name = "_user")
public class User {

    /**
     * Primary key for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Integer id;

    /**
     * Username used for login and identification.
     */
    @Column(name = "username")
    private String username;

    /**
     * Password used for authentication.
     * Should be securely hashed and stored.
     */
    @Column(name = "password")
    private String password;

    /**
     * User role defining access level (e.g. DOCTOR, NURSE, CHEF, HEADCHEF).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role")
    private Role role;

    /**
     * Constructor to manually set ID, username and password.
     * Mainly used for tests or manual creation.
     *
     * @param id       the user ID
     * @param username the username
     * @param password the password
     */
    public User(Integer id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }
}
