### Create new order
POST http://localhost:7070/api/orders
Content-Type: application/json

{
  "dishId": 1,
  "patientId": 1234,
  "orderDate": "2025-05-06"
}

### Get order by ID
GET http://localhost:7070/api/orders/1

### Get all orders for a patient
GET http://localhost:7070/api/orders?patientId=1234

### Delete order
DELETE http://localhost:7070/api/orders/1
