@startuml

top to bottom direction
skinparam linetype ortho

class _order {
   bed_id: integer
   note: varchar(255)
   order_time: timestamp(6)
   status: varchar(255)
   id: integer
}
class bed {
   occupied: boolean
   patient_name: varchar(255)
   section_id: bigint
   id: integer
}
class dish {
   available_from: date
   available_until: date
   carbohydrates: double precision
   description: varchar(255)
   fat: double precision
   kcal: double precision
   name: varchar(255)
   protein: double precision
   status: varchar(255)
   recipe_id: integer
   id: integer
}
class dish_allergens {
   dish_id: integer
   allergen: varchar(255)
}
class employee {
   email: varchar(255)
   first_name: varchar(255)
   last_name: varchar(255)
   middle_name: varchar(255)
   password: varchar(255)
   roles: varchar(255) []
   id: bigint
}
class employee_section {
   employee_id: bigint
   section_id: bigint
}
class event {
   description: text
   dur: numeric(21)
   name: varchar(255)
   start_time: timestamp(6)
   id: integer
}
class examtreat {
   article: text
   description: varchar(255)
   name: varchar(255)
   src_url: varchar(255)
   exam_treatment_type: integer
   id: integer
}
class examtreatcategory {
   description: varchar(255)
   name: varchar(255)
   id: integer
}
class examtreattype {
   description: varchar(255)
   name: varchar(255)
   exam_treatment_category: integer
   id: integer
}
class ingredient {
   recipe_id: integer
   ingredient_type_id: integer
   id: integer
}
class ingredient_type {
   name: varchar(255)
   id: integer
}
class order_dish {
   dish_id: integer
   order_id: integer
}
class recipe {
   instructions: text
   title: varchar(255)
   dish_id: integer
   id: integer
}
class roles {
   name: varchar(20)
}
class section {
   name: varchar(255)
   id: bigint
}
class user_roles {
   user_name: varchar(25)
   role_name: varchar(20)
}
class users {
   password: varchar(255)
   username: varchar(25)
}

_order             --^  bed               : "bed_id:id"
bed                --^  section           : "section_id:id"
dish               --^  recipe            : "recipe_id:id"
dish_allergens     --^  dish              : "dish_id:id"
employee_section   --^  employee          : "employee_id:id"
employee_section   --^  employee          : "section_id:id"
employee_section   --^  section           : "employee_id:id"
employee_section   --^  section           : "section_id:id"
examtreat          --^  examtreattype     : "exam_treatment_type:id"
examtreattype      --^  examtreatcategory : "exam_treatment_category:id"
ingredient         --^  ingredient_type   : "ingredient_type_id:id"
ingredient         --^  recipe            : "recipe_id:id"
order_dish         --^  _order            : "order_id:id"
order_dish         --^  dish              : "dish_id:id"
recipe             --^  dish              : "dish_id:id"
user_roles         --^  roles             : "role_name:name"
user_roles         --^  users             : "user_name:username"
@enduml
